// data.jsx

const bacteriaData = [
  {
    id: 1,
    name: "Escherichia coli",
    group: "Gram-negative",
    image: "/images/bacteria/Ecoli-CCA.jpg",
    description: "A common gut bacterium, some strains are harmless while others can cause food poisoning.",
    shape: "Bacillus (rod-shaped)",
    colour: "Blue-Purple (Gram-negative)",
    specificAgar: "Chromogenic coliform agar (Blue-purple color)",
    genericAgar: "Nutrient agar, Blood agar",
  },
  {
    id: 2,
    name: "Staphylococcus aureus",
    group: "Gram-positive",
    image: "/images/bacteria/staphylococcus.webp",
    description: "Often found on the skin and in the nose; can cause infections if it enters the body.",
    shape: "Coccus (spherical, clusters)",
    colour: "Purple (Gram-positive)",
    specificAgar: "Mannitol salt agar (ferments mannitol → yellow colonies)",
    genericAgar: "Blood agar, Nutrient agar",
  },
  {
    id: 3,
    name: "Bacillus subtilis",
    group: "Gram-positive",
    image: "/images/bacteria/bacillus_subtilis.jpg",
    description: "A soil bacterium widely used in research and biotechnology.",
    shape: "Bacillus (rod-shaped)",
    colour: "Purple (Gram-positive)",
    specificAgar: "Nutrient agar (large, dry colonies with irregular edges)",
    genericAgar: "Tryptic soy agar, Blood agar",
  },
  {
    id: 4,
    name: "Salmonella enterica",
    group: "Gram-negative",
    image: "/images/bacteria/salmonella.JPG",
    description: "A major cause of foodborne illness worldwide.",
    shape: "Bacillus (rod-shaped)",
    colour: "Pink (Gram-negative)",
    specificAgar: "XLD agar (red colonies with black centers)",
    genericAgar: "Nutrient agar, MacConkey agar",
  },
  {
    id: 5,
    name: "Streptococcus pneumoniae",
    group: "Gram-positive",
    image: "/images/bacteria/streptococcus_pneumoniae.jpeg",
    description: "Causes pneumonia, meningitis, and other serious infections.",
    shape: "Coccus (spherical, chains)",
    colour: "Purple (Gram-positive)",
    specificAgar: "Blood agar (alpha-hemolysis → greenish zone)",
    genericAgar: "Chocolate agar, Nutrient agar",
  },
  {
    id: 6,
    name: "Pseudomonas aeruginosa",
    group: "Gram-negative",
    image: "/images/bacteria/pseudomonas.jpeg",
    description: "An opportunistic pathogen often found in hospitals, resistant to many antibiotics.",
    shape: "Bacillus (rod-shaped)",
    colour: "Pink (Gram-negative)",
    specificAgar: "Cetrimide agar (produces green/blue pigment pyocyanin)",
    genericAgar: "Nutrient agar, MacConkey agar",
  },
  {
    id: 7,
    name: "Clostridium botulinum",
    group: "Gram-positive",
    image: "/images/bacteria/clostridium_botulinum.jpg",
    description: "Produces botulinum toxin, one of the most powerful toxins known.",
    shape: "Bacillus (rod-shaped, spore-forming)",
    colour: "Purple (Gram-positive)",
    specificAgar: "Egg yolk agar (lipase activity test)",
    genericAgar: "Anaerobic blood agar, Nutrient agar",
  },
  
];

export default bacteriaData;
