// data.jsx

const BacteriaData = [
  {
    id: 1,
    name: "Escherichia coli",
    group: "Gram-negative",
    image: "/images/Ecoli-CCA.png",
    description: "A common gut bacterium, some strains are harmless while others can cause food poisoning.",
    shape: "Bacillus (rod-shaped)",
    colour: "Pink (Gram-negative)",
    specificAgar: "MacConkey agar (lactose fermenter → pink colonies)",
    genericAgar: "Nutrient agar, Blood agar",
  },
  {
    id: 2,
    name: "Staphylococcus aureus",
    group: "Gram-positive",
    image: "/images/bacteria/staphylococcus.jpg",
    description: "Often found on the skin and in the nose; can cause infections if it enters the body.",
    shape: "Coccus (spherical, clusters)",
    colour: "Purple (Gram-positive)",
    specificAgar: "Mannitol salt agar (ferments mannitol → yellow colonies)",
    genericAgar: "Blood agar, Nutrient agar",
  },
  {
    id: 3,
    name: "Bacillus subtilis",
    group: "Gram-positive",
    image: "/images/bacteria/bacillus_subtilis.jpg",
    description: "A soil bacterium widely used in research and biotechnology.",
    shape: "Bacillus (rod-shaped)",
    colour: "Purple (Gram-positive)",
    specificAgar: "Nutrient agar (large, dry colonies with irregular edges)",
    genericAgar: "Tryptic soy agar, Blood agar",
  },
  {
    id: 4,
    name: "Salmonella enterica",
    group: "Gram-negative",
    image: "/images/bacteria/salmonella.jpg",
    description: "A major cause of foodborne illness worldwide.",
    shape: "Bacillus (rod-shaped)",
    colour: "Pink (Gram-negative)",
    specificAgar: "XLD agar (red colonies with black centers)",
    genericAgar: "Nutrient agar, MacConkey agar",
  },
  {
    id: 5,
    name: "Streptococcus pneumoniae",
    group: "Gram-positive",
    image: "/images/bacteria/streptococcus_pneumoniae.jpg",
    description: "Causes pneumonia, meningitis, and other serious infections.",
    shape: "Coccus (spherical, chains)",
    colour: "Purple (Gram-positive)",
    specificAgar: "Blood agar (alpha-hemolysis → greenish zone)",
    genericAgar: "Chocolate agar, Nutrient agar",
  },
  {
    id: 6,
    name: "Pseudomonas aeruginosa",
    group: "Gram-negative",
    image: "/images/bacteria/pseudomonas.jpg",
    description: "An opportunistic pathogen often found in hospitals, resistant to many antibiotics.",
    shape: "Bacillus (rod-shaped)",
    colour: "Pink (Gram-negative)",
    specificAgar: "Cetrimide agar (produces green/blue pigment pyocyanin)",
    genericAgar: "Nutrient agar, MacConkey agar",
  },
  {
    id: 7,
    name: "Clostridium botulinum",
    group: "Gram-positive",
    image: "/images/bacteria/clostridium_botulinum.jpg",
    description: "Produces botulinum toxin, one of the most powerful toxins known.",
    shape: "Bacillus (rod-shaped, spore-forming)",
    colour: "Purple (Gram-positive)",
    specificAgar: "Egg yolk agar (lipase activity test)",
    genericAgar: "Anaerobic blood agar, Nutrient agar",
  },
  {
    id: 8,
    name: "Neisseria meningitidis",
    group: "Gram-negative",
    image: "/images/bacteria/neisseria.jpg",
    description: "Causes meningitis and bloodstream infections.",
    shape: "Coccus (spherical, pairs)",
    colour: "Pink (Gram-negative)",
    specificAgar: "Chocolate agar (with CO₂ incubation)",
    genericAgar: "Blood agar, Nutrient agar",
  },
  {
    id: 9,
    name: "Mycobacterium tuberculosis",
    group: "Acid-fast (not classic Gram)",
    image: "/images/bacteria/mycobacterium_tb.jpg",
    description: "The bacterium responsible for tuberculosis (TB).",
    shape: "Bacillus (rod-shaped)",
    colour: "Acid-fast red (Ziehl–Neelsen stain)",
    specificAgar: "Lowenstein–Jensen medium (slow growth)",
    genericAgar: "Middlebrook agar",
  },
  {
    id: 10,
    name: "Vibrio cholerae",
    group: "Gram-negative",
    image: "/images/bacteria/vibrio_cholerae.jpg",
    description: "Causes cholera, a severe diarrheal disease spread by contaminated water.",
    shape: "Vibrio (comma-shaped rod)",
    colour: "Pink (Gram-negative)",
    specificAgar: "TCBS agar (yellow colonies due to sucrose fermentation)",
    genericAgar: "Nutrient agar, Blood agar",
  },
];

export default BacteriaData;
